### ISSUE TITLE
Please explain this

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/crypto-kitties#2]
why just don't use `string + id` ?)

![image](https://user-images.githubusercontent.com/8848858/51200976-8f393c80-1903-11e9-8fa5-7aff530084cd.png)

**Comment by IgnatSemchuk** [comment]
Using unspecified number of arguments allows you to change the hash generation parameters without changing the function

**Comment by rudnitskih** [comment]
Trust me, what you did is https://en.wikipedia.org/wiki/Overengineering

**Comment by rudnitskih** [comment]
https://en.wikipedia.org/wiki/KISS_principle

**Comment by rudnitskih** [comment]
Also, this function render nothing - correct name can be `getKittenColor(kitten) {` Yes, you function will accept full kitten object and will use needed properties to generate hash and get color from hash.

**Comment by IgnatSemchuk** [comment]
And its is more consistent! All functions will manipulate by objects. I'm correct?

**Comment by rudnitskih** [comment]
Passing whole object is not always good practice, but in this case I think the code will be more elegant
