### ISSUE TITLE
Why do you create extra modificators?

### ISSUE THREAD

**Issue by rudnitskih** [IgnatSemchuk/crypto-kitties#3]
![image](https://user-images.githubusercontent.com/8848858/51201109-e0e1c700-1903-11e9-9577-a9708962e54c.png)

![image](https://user-images.githubusercontent.com/8848858/51201152-fbb43b80-1903-11e9-8857-7497ec39b920.png)

**Comment by IgnatSemchuk** [comment]
I read this in the BEM [spec](https://ru.bem.info/methodology/naming-convention/)
![image](https://user-images.githubusercontent.com/22999658/51209900-0a0d5200-191a-11e9-9dbb-034826895273.png)

**Comment by rudnitskih** [comment]
The syntax is correct, the question is why you created modificators if you could write these styles directly in elements/blocks

**Comment by IgnatSemchuk** [comment]
Is my implementation too much fragmented? If I've understood correct, its is KISS violation. 
Since I use only one type of component, I have to implement the component style simpler. I create base classes, and add new modifiers when I enter a new component type.
